# Generated by Django 5.0.6 on 2024-09-01 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungucode', models.IntegerField()),
                ('addr1', models.TextField()),
                ('addr2', models.TextField()),
                ('image', models.TextField(null=True)),
                ('cat1', models.CharField(max_length=3)),
                ('cat2', models.CharField(max_length=5)),
                ('cat3', models.CharField(max_length=9)),
                ('type_id', models.IntegerField()),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('title', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('eventstartdate', models.DateTimeField(null=True)),
                ('eventenddate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_num', models.IntegerField()),
                ('tour_type', models.CharField(max_length=10, null=True)),
                ('group_name', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(related_name='joined_group', through='createDB.Group_Members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group_members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.groups'),
        ),
        migrations.CreateModel(
            name='Routes_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=20)),
                ('lodge', models.TextField()),
                ('route_area', models.IntegerField()),
                ('tour_startdate', models.DateTimeField(blank=True, null=True)),
                ('tour_enddate', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='createDB.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_plan_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_seq', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.routes_plan')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.tours')),
            ],
        ),
        migrations.AddField(
            model_name='routes_plan',
            name='route_details',
            field=models.ManyToManyField(related_name='get_routes', through='createDB.Tour_plan_data', to='createDB.tours'),
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.IntegerField(null=True)),
                ('user_type', models.TextField(null=True)),
                ('user_healing', models.IntegerField(null=True)),
                ('user_relax', models.IntegerField(null=True)),
                ('user_nature', models.IntegerField(null=True)),
                ('user_exhibit', models.IntegerField(null=True)),
                ('user_food', models.IntegerField(null=True)),
                ('user_adventure', models.IntegerField(null=True)),
                ('user_people', models.IntegerField(null=True)),
                ('user_shopping', models.IntegerField(null=True)),
                ('user_photo', models.IntegerField(null=True)),
                ('tour_dislike', models.ManyToManyField(related_name='disliked_users', to='createDB.tours')),
                ('tour_like', models.ManyToManyField(related_name='liked_users', to='createDB.tours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
