# Generated by Django 4.2.6 on 2024-09-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_group_region'),
        ('createDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_num', models.IntegerField()),
                ('tour_type', models.CharField(max_length=10, null=True)),
                ('group_name', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.AlterField(
            model_name='group_members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.groupinfo'),
        ),
        migrations.AlterField(
            model_name='routes_plan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='createDB.groupinfo'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
