# Generated by Django 4.2.6 on 2024-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDB', '0002_remove_user_info_tour_like_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_adventure',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_exhibit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_food',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_healing',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_nature',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_people',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_photo',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_relax',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_shopping',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_type',
            field=models.TextField(default='힐링형 감자'),
        ),
    ]
