# Generated by Django 4.2.6 on 2024-09-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('createDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTourOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('group_tour_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_tour.grouptourlist')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.tours')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('group_tour_list', 'tour')},
            },
        ),
        migrations.AddField(
            model_name='grouptourlist',
            name='tour_list',
            field=models.ManyToManyField(through='group_tour.GroupTourOrder', to='createDB.tours'),
        ),
    ]
