# Generated by Django 4.2.6 on 2024-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_tour', '0002_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
