# Generated by Django 5.0.6 on 2024-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="010-0000-0000", max_length=20),
            preserve_default=False,
        ),
    ]
