# Generated by Django 4.2.6 on 2024-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
