# Generated by Django 4.2.6 on 2024-09-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_type', models.CharField(max_length=255)),
                ('character_description', models.TextField()),
                ('recommend_place', models.CharField(max_length=10)),
                ('recommend_reason', models.TextField()),
                ('best_match', models.CharField(max_length=20)),
                ('match_reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
