# Generated by Django 5.0.6 on 2024-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('free', '자유게시판'), ('travel', '여행 후기 게시판'), ('notice', '공지사항 게시판')], default='free', max_length=20),
        ),
    ]
