# Generated by Django 4.2.6 on 2024-08-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_is_reported'),
        ('board', '0003_post_liked_users'),
    ]

    operations = [
    ]
