# Generated by Django 4.2.6 on 2024-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_merge_0002_post_is_reported_0003_post_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='report_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('free', '자유게시판'), ('travel', '여행 후기 게시판'), ('notice', '공지사항 게시판')], db_index=True, default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_reported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='report_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at', 'board_type'], name='board_post_created_c71227_idx'),
        ),
    ]
